- hosts: all
  become: true
  tasks:
    - name: Fetch rule data from URL
      uri:
        url: https://stats.osbornetech.support/ansible/ufw/ufw_rules.yaml
        method: GET
        return_content: yes
      register: rule_data
      ignore_errors: true
      check_mode: no

    - name: Parse YAML data for rules
      set_fact:
        rule_list: "{{ rule_data.content | from_yaml }}"
      when: rule_data.content is defined and rule_data.status == 200
      ignore_errors: true

    - name: Check if YAML parsing failed or URL fetch failed
      fail:
        msg: "Failed to parse YAML data or fetch URL for rules. Check 'rule_data' for details."
      when: rule_list is undefined or rule_data.failed or rule_data.status != 200

    - name: Disable UFW
      shell: ufw disable
      changed_when: true

    - name: Remove all existing UFW rules
      shell: sudo ufw status numbered | sed -n 's/^\s*\[\s*\([0-9]\+\)\].*/\1/p' | xargs -I {} sudo ufw delete {}
      changed_when: true

    - name: Add UFW rules for allowed IPs
      block:
        - name: Check for existing rules
          shell: ufw status numbered | wc -l
          register: ufw_rule_count
          changed_when: false

        - name: Add rules with insert if rules exist
          ufw:
            rule: allow
            from_ip: "{{ item.port }}"
            comment: "{{ item.comment | default('Managed by Ansible') }}"
            insert: "{{ item.rule_num | int }}"
          loop: "{{ rule_list }}"
          when: ufw_rule_count.stdout | int > 0

        - name: Add rules without insert if no rules exist
          ufw:
            rule: allow
            from_ip: "{{ item.port }}"
            comment: "{{ item.comment | default('Managed by Ansible') }}"
          loop: "{{ rule_list }}"
          when: ufw_rule_count.stdout | int == 0

    - name: Enable UFW
      shell: yes | sudo ufw enable
      changed_when: true
