- hosts: all
  become: true
  tasks:
    - name: Fetch rule data from URL
      uri:
        url: https://stats.osbornetech.support/ansible/ufw/ufw_rules.yaml
        method: GET
        return_content: yes
      register: rule_data
      ignore_errors: true
      check_mode: no

    - name: Parse YAML data for rules
      set_fact:
        rule_list: "{{ rule_data.content | from_yaml }}"
      when: rule_data.content is defined and rule_data.status == 200
      ignore_errors: true

    - name: Check if YAML parsing failed or URL fetch failed
      fail:
        msg: "Failed to parse YAML data or fetch URL for rules. Check 'rule_data' for details."
      when: rule_list is undefined or rule_data.failed or rule_data.status != 200

    - name: Disable UFW
      shell: ufw disable
      changed_when: true

    - name: Remove all existing UFW rules
      shell: ufw status numbered | sed -n 's/^\s*\[\s*\([0-9]\+\)\].*/\1/p' | xargs -I {} ufw delete {}
      changed_when: true

    - name: Add UFW rules for allowed IPs
      ufw:
        rule: allow
        from_ip: "{{ item.port }}"
        comment: "{{ item.comment | default('Managed by Ansible') }}"
        insert: "{{ item.rule_num }}"
      loop: "{{ rule_list }}"
      when: rule_list is defined

    - name: Enable UFW
      shell: yes | sudo ufw enable
      changed_when: true
