---
- hosts: all
  become: true
  tasks:
    - name: Fetch IP data from URL
      uri:
        url: https://stats.osbornetech.support/ansible/ufw/ufw_rules.json
        method: GET
        return_content: yes
      register: ip_data
      ignore_errors: true
      check_mode: no

    - name: Parse JSON data
      set_fact:
        ip_list: "{{ ip_data.content | from_json }}"
      when: ip_data.content is defined and ip_data.status == 200
      ignore_errors: true

    - name: Check if JSON parsing failed or URL fetch failed
      fail:
        msg: "Failed to parse JSON data or fetch URL. Check 'ip_data' for details."
      when: ip_list is undefined or ip_data.failed or ip_data.status != 200

    - name: Add UFW rules for allowed IPs
      ufw:
        rule: allow
        from_ip: "{{ item.port }}"
        comment: "{{ item.comment | default('Managed by Ansible') }}"
      loop: "{{ ip_list }}"
      when: ip_list is defined

    - name: Gather existing UFW rules
      shell: ufw status numbered | grep -E "^\[[[:space:]]*[[:digit:]]+]"
      register: current_ufw_rules
      changed_when: false

    - name: Extract rule numbers to delete
      set_fact:
        rules_to_delete: >-
          {% set delete_list = [] %}
          {% set allowed_nums = ip_list | map(attribute='rule_num') | list %}
          {% for line in current_ufw_rules.stdout_lines %}
            {% if line is match('^\\[\\s*\\d+\\]') %}
              {% set num = line.split('[')[1].split(']')[0]|trim %}
              {% if num | int not in allowed_nums %}
                {{ delete_list.append(num) or '' }}
              {% endif %}
            {% endif %}
          {% endfor %}
          {{ delete_list }}
      when: ip_list is defined

    - name: Debug rules to delete
      debug:
        var: rules_to_delete

    - name: Remove outdated UFW rules
      ufw:
        state: absent
        delete: yes
        rule_num: "{{ item }}"
      loop: "{{ rules_to_delete | map('int') | list }}"
      when: rules_to_delete | length > 0
