---
- hosts: all
  become: true
  tasks:
    - name: Fetch rule data from URL
      uri:
        url: https://stats.osbornetech.support/ansible/ufw/ufw_rules.yaml
        method: GET
        return_content: yes
      register: rule_data
      ignore_errors: true
      check_mode: no

    - name: Parse YAML data for rules
      set_fact:
        rule_list: "{{ rule_data.content | from_yaml }}"
      when: rule_data.content is defined and rule_data.status == 200
      ignore_errors: true

    - name: Check if YAML parsing failed or URL fetch failed
      fail:
        msg: "Failed to parse YAML data or fetch URL for rules. Check 'rule_data' for details."
      when: rule_list is undefined or rule_data.failed or rule_data.status != 200

    - name: Add UFW rules for allowed IPs
      ufw:
        rule: allow
        from_ip: "{{ item.port }}"
        comment: "{{ item.comment | default('Managed by Ansible') }}"
      loop: "{{ rule_list }}"
      when: rule_list is defined

    - name: Gather existing UFW rules
      shell: ufw status numbered | grep -E "^\[[[:space:]]*[[:digit:]]+]"
      register: current_ufw_rules
      changed_when: false

    - name: Extract rule numbers to delete
      set_fact:
        rules_to_delete: >-
          {% set delete_list = [] %}
          {% set allowed_nums = rule_list | map(attribute='rule_num') | map('string') | list %}
          {% for line in current_ufw_rules.stdout_lines %}
            {% if line is match('^\\[\\s*\\d+\\]') %}
              {% set num = line.split('[')[1].split(']')[0]|trim %}
              {% if num not in allowed_nums %}
                {{ delete_list.append(num) or '' }}
              {% endif %}
            {% endif %}
          {% endfor %}
          {{ delete_list }}
      when: rule_list is defined

    - name: Debug rules to delete
      debug:
        var: rules_to_delete

    - name: Remove outdated UFW rules
      command: "ufw --force delete {{ item }}"
      loop: "{{ rules_to_delete }}"
      when: rules_to_delete is defined and rules_to_delete | length > 0
