---
- hosts: all
  become: true
  tasks:
    - name: Fetch port data from URL
      uri:
        url: https://stats.osbornetech.support/ansible/ufw/ufw_rules.json
        method: GET
        return_content: yes
      register: port_data
      ignore_errors: true
      check_mode: no

    - name: Debug port_data content
      debug:
        var: port_data.content
      when: port_data.content is defined

    - name: Debug failed status
      debug:
        var: port_data.failed
      when: port_data.failed is defined

    - name: Debug msg status
      debug:
        var: port_data.msg
      when: port_data.msg is defined

    - name: Debug status code
      debug:
        var: port_data.status
      when: port_data.status is defined

    - name: Parse JSON data
      set_fact:
        ip_list: "{{ port_data.content | from_json }}"
      when: port_data.content is defined and port_data.status == 200
      ignore_errors: true

    - name: Check if JSON parsing failed or URL fetch failed
      fail:
        msg: "Failed to parse JSON data or fetch URL. Check 'port_data' for details."
      when: ip_list is undefined or port_data.failed or port_data.status != 200

    - name: Ensure Ansible server IP is allowed
      ufw:
        rule: allow
        src: "192.168.0.34"
        comment: "Allow Ansible server"

    - name: Configure UFW rules from ip_list
      block:
        - name: Add UFW rules from the ip_list
          ufw:
            rule: allow
            src: "{{ item.port }}"
            comment: "{{ item.comment | default('Managed by Ansible') }}"
          loop: "{{ ip_list }}"
          when: item.port != "192.168.0.34"

        - name: Remove existing UFW rules for IPs in the list not in JSON
          ufw:
            rule: delete
            src: "{{ item.port }}"
          loop: "{{ ip_list }}"
          when: item.port != "192.168.0.34"

      when: ip_list is defined
