---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Reboot the server
      reboot:
        connect_timeout: 5
        reboot_timeout: 300

    - name: Send Discord notification
      uri:
        url: "https://discord.com/api/webhooks/1328286109838610463/K9_0-0TfsXwKbSzrARvxLAbL819QsVBzh80oC2qPQ4J1ZVkIJD-M4FynnCPYqJIfTlqF"
        method: POST
        headers:
          Content-Type: "application/json"
        body: '{"content": "Server upgrade complete!"}'
        body_format: json
