---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages excluding docker
      apt:
        upgrade: dist
        exclude: docker*, containerd*
