---
- hosts: all
  become: true
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        
    # Check if reboot is required
    - name: check if system reboot is required
      become: yes
      stat:
        path: /var/run/reboot-required
      required: reboot_required

    - name: Send Discord notification
      uri:
        url: "https://discord.com/api/webhooks/1328286109838610463/K9_0-0TfsXwKbSzrARvxLAbL819QsVBzh80oC2qPQ4J1ZVkIJD-M4FynnCPYqJIfTlqF"
        method: POST
        headers:
          Content-Type: "application/json"
        status_code: 204
        body: '{"content": "Reboot required on {{ inventory_hostname }}"}'
        body_format: json
      when: reboot_required.stat.exists
